[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[phases.start]
cmd = "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/auth-backend-0.0.1-SNAPSHOT.jar"

[variables]
MAVEN_OPTS = "-Xmx1024m"