[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/auth-backend-0.0.1-SNAPSHOT.jar"

[variables]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"
NIXPACKS_JAVA_VERSION = "17"

[build.env]
MAVEN_OPTS = "-Xmx1024m"